### ISSUE TITLE
a Question about CPU

### ISSUE THREAD

**Issue by hoaug-tran** [nakquada/Z790-Hackintosh#1]
Do you use macOS with the option to disable E core and only Enable P core + Hyperthreading or do you use it with the option to enable both E core and P core and Hyperthreading?

**Comment by nakquada** [comment]
Hi there,

I use it with all cores and HT enabled.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: hoaug ***@***.***>
Sent: Sunday, June 25, 2023 9:29:26 AM
To: nakquada/Z790-Hackintosh ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nakquada/Z790-Hackintosh] a Question about CPU (Issue #1)


Do you use macOS with the option to disable E core and only Enable P core + Hyperthreading or do you use it with the option to enable both E core and P core and Hyperthreading?
